# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cacheresult_geographiccoordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheValidResult',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('core.cacheresult',),
        ),
        migrations.AddField(
            model_name='cacheresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
