# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170204_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheresult',
            name='cache_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='cacheresult',
            unique_together=set([('lat', 'lng')]),
        ),
        migrations.AlterUniqueTogether(
            name='geographiccoordinate',
            unique_together=set([('lat', 'lng', 'address')]),
        ),
    ]
