# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170205_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, protocol='IPv4'),
        ),
        migrations.AlterIndexTogether(
            name='cacheresult',
            index_together=set([('lat', 'lng')]),
        ),
    ]
