# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170205_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographiccoordinate',
            name='search_address',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
